# chaosmonkey
spring:
  profiles:
    active: chaos-monkey

# actuator
management:
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, chaosmonkey

# repository watcher ??? - watcher(?? ??)
chaos:
  monkey:
    watcher:
      repository: true
      rest-controller: true